### PR TITLE
renamed tf submodule to net

### PR DESCRIPTION
**Pull request by kevjshih**

### CODE REVIEW

**Comment by kevjshih** [comment]
@BigRedT @tomlepaine 

Trivial pull request, but I wanted to try out the system too and run the renaming scheme by you guys.

**Comment by BigRedT** [comment]
tom and thought tflow might be a good name because it indicates its related to tensorflow, is short, and can not be easily confused with tf

**Comment by kevjshih** [comment]
I'm probably being pedantic here, but I was hoping to stick to something that had a similar meaning to the original tf_utils, rather than an abbreviation of tensorflow, since it's a going to be more of a wrapper than a fork of tf. Ideally it'd be something such that when someone was reading your code, it'd be clear to them that you're not importing another implentation of tensorflow.

**Comment by kevjshih** [comment]
I'd be ok with switching it back to tf_utils for this one, but keeping the shorter vis and lang module names.

**Comment by saurabhme** [comment]
It might be a good idea to keep the umbrella module name short e.g. tfu, as it will be used often. Further short name makes it easy to fit things in 80 cols. Usually it's not a good idea to have such acronyms as names, but there is a reason why tf is tf.

**Comment by kevjshih** [comment]
Tanmay and I decided maybe tftools? It's short enough, and maybe we should all just import it as tfu.

**Comment by saurabhme** [comment]
Makes sense.

**Pull request merged**
