### PR TITLE
Restructure repo

### PR DESCRIPTION
**Pull request by tomlepaine**
@BigRedT @kevjshih 

This is a proposal to restructure the repo a little bit.

It has three main changes:
1) Use typical python repo structure. I think most python repos on github uses this structure:

```
./library/
./library/__init__.py
./README.md
./.gitignore
```

Basically it is the same as we are using now, but with an internal directory for the library, so that other code which we might like to make separate from the library (for example scripts) can have a place to live as well.

2) Name the library **aiutils** because the py is redundant when important in python :smile:

3) Also in the name of reducing redundancy, lets shorten the names of the submodules to:
- lang
- tf
- vis

---

Additional things I snuck in:
- I added a **data** submodule just for fun.
- I reformatted `README.md` to use the type of markdown formatting I prefer. Feel free to tell me to change it back. Hooray pull requests!

And mostly I am making this a pull request to play around with making pull requests :imp:

### CODE REVIEW

**Comment by BigRedT** [comment]
I haven't pulled you request yet to prevent you from going through the pain of resolving conflicts due to my pull request.

**Comment by kevjshih** [comment]
Wouldn't renaming the submodule to 'tf' conflict with the typical renaming scheme of tensorflow->tf, in which case you'd have both import tensorflow as tf, but also an import tf from aiutils?

**Comment by tomlepaine** [comment]
Please go ahead and do it. I will report back on how painful the merge is.
I think it might be relatively easy :)

**Comment by BigRedT** [comment]
it would if you do:
`import aiutils.tf`
not if you do:
`import aiutils` (using the functions as aiutils.tf.func)
or if you do:
`import aiutils.tf as tf_utils`  (using the functions as tf_utils.func)

**Comment by tomlepaine** [comment]
@kevjshih 
It does. But there is lots of flexibility in python imports.

We could set it up to `import aiutils` and then call `aiutils.tf`.
We could do `from aituils import tf as aitf`.

I still think we should remove the redundancy, but I am open to suggestions for an alternative to `tf`.

**Comment by kevjshih** [comment]
Right, I'm just suggesting something other than 'tf' here because the default import without renaming would conflict with common practice for importing tensorflow, which might cause a bug if someone isn't careful. 'nn' or 'aitf' are all fine by me.

**Comment by kevjshih** [comment]
Actually nn isn't great either because tf also has an 'nn' submodule, I think.

**Comment by BigRedT** [comment]
can also call it tflow 
@tomlepaine you might wanna make the change while you deal with merge conflicts

**Comment by kevjshih** [comment]
How about 'net.' I think that's generic/short enough and allows for the possibility of including non-tensorflow stuff should the occasion arise.

**Pull request merged**
