### PR TITLE
:art: Moved tests to their own directory + Add requirements.txt

### PR DESCRIPTION
**Pull request by tomlepaine**
The title says it all.

## Tests
This [website](http://docs.python-guide.org/en/latest/writing/structure/#structure-of-the-repository) suggests moving the tests into their own directory at the root of the repo. It also suggests a way of import things to make the tests work.

Assuming you have `py.test` installed, now you can run all the tests from the root of the repo using:

``` bash
> py.test
```

## Requirements
In theory, to install all our dependencies you just need to run:

``` bash
> pip install -r requirements.txt
```

### CODE REVIEW

**Comment by arunmallya** [comment]
Quick question: should we keep all layer tests in one file or in separate files?
If we move on to other CI tools, what would be best?

**Comment by tomlepaine** [comment]
I think putting them all in a single directory is preferred and better for CI, according to the website I linked.

**Comment by tomlepaine** [comment]
Also, I checked `py.test` works with **Travis CI** if we want to do that.

**Comment by arunmallya** [comment]
LGTM

**Pull request merged**
